name: flutter_pdfium_ios
description: 'A new Flutter plugin project.'
version: 0.0.1
homepage: asdf

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterPdfiumIosPlugin
