name: flutter_pdfium_example
description: 'Demonstrates how to use the flutter_pdfium plugin.'
publish_to: 'none'

version: 0.0.0-development

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_pdfium:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/
