name: flutter_pdfium_example
description: 'Demonstrates how to use the flutter_pdfium plugin.'
publish_to: 'none'

version: 0.0.0-development

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  fluorflow: ^3.1.0
  flutter:
    sdk: flutter
  flutter_pdfium:
    path: ../

dev_dependencies:
  build_runner: ^2.0.0
  fluorflow_generator: ^3.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
