name: flutter_pdfium

# repository: https://github.com/TODO

packages:
  - packages/flutter_pdfium*
  - packages/example

scripts:
  build_runner:
    description: Run build_runner
    exec: dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn:
        - build_runner

  ffigen:
    description: Generate FFI bindings
    exec: dart run ffigen --config ffigen.yaml
    packageFilters:
      dependsOn:
        - ffigen

ide:
  intellij:
    enabled: false
