name: flutter_pdfium
description: 'Dart FFI bindings for PDFium library. Downloads and links the library upon build.'
version: 0.0.0-development
homepage: https://github.com/buehler/flutter_pdfium
repository: https://github.com/buehler/flutter_pdfium.git
issue_tracker: https://github.com/buehler/flutter_pdfium/issues

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^12.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
