name: flutter_pdfium
description: 'A new Flutter FFI plugin project.'
version: 0.0.0-development
homepage: sadf

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  ffigen: ^12.0.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
