name: flutter_pdfium
description: 'A new Flutter package project.'
version: 0.0.1
homepage: asdf

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  flutter_pdfium_windows:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  ffigen: ^11.0.0

flutter:
