name: flutter_pdfium_linux
description: 'A new Flutter FFI plugin project.'
version: 0.0.1
homepage: hjuik

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
