
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#if _WIN32
#include <windows.h>
#else
#include <pthread.h>
#include <unistd.h>
#endif

#if _WIN32
#define FFI_PLUGIN_EXPORT __declspec(dllexport)
#else
#define FFI_PLUGIN_EXPORT
#endif

#include "pdfium/fpdf_transformpage.h"
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_SetMediaBox(FPDF_PAGE page,float left,float bottom,float right,float top);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_SetCropBox(FPDF_PAGE page,float left,float bottom,float right,float top);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_SetBleedBox(FPDF_PAGE page,float left,float bottom,float right,float top);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_SetTrimBox(FPDF_PAGE page,float left,float bottom,float right,float top);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_SetArtBox(FPDF_PAGE page,float left,float bottom,float right,float top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_GetMediaBox(FPDF_PAGE page,float * left,float * bottom,float * right,float * top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_GetCropBox(FPDF_PAGE page,float * left,float * bottom,float * right,float * top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_GetBleedBox(FPDF_PAGE page,float * left,float * bottom,float * right,float * top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_GetTrimBox(FPDF_PAGE page,float * left,float * bottom,float * right,float * top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_GetArtBox(FPDF_PAGE page,float * left,float * bottom,float * right,float * top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_TransFormWithClip(FPDF_PAGE page,const FS_MATRIX * matrix,const FS_RECTF * clipRect);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPageObj_TransformClipPath(FPDF_PAGEOBJECT page_object,double a,double b,double c,double d,double e,double f);
FFI_PLUGIN_EXPORT FPDF_CLIPPATH PDFIUM_FPDFPageObj_GetClipPath(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFClipPath_CountPaths(FPDF_CLIPPATH clip_path);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFClipPath_CountPathSegments(FPDF_CLIPPATH clip_path,int path_index);
FFI_PLUGIN_EXPORT FPDF_PATHSEGMENT PDFIUM_FPDFClipPath_GetPathSegment(FPDF_CLIPPATH clip_path,int path_index,int segment_index);
FFI_PLUGIN_EXPORT FPDF_CLIPPATH PDFIUM_FPDF_CreateClipPath(float left,float bottom,float right,float top);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_DestroyClipPath(FPDF_CLIPPATH clipPath);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_InsertClipPath(FPDF_PAGE page,FPDF_CLIPPATH clipPath);
#include "pdfium/fpdf_annot.h"
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_IsSupportedSubtype(FPDF_ANNOTATION_SUBTYPE subtype);
FFI_PLUGIN_EXPORT FPDF_ANNOTATION PDFIUM_FPDFPage_CreateAnnot(FPDF_PAGE page,FPDF_ANNOTATION_SUBTYPE subtype);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPage_GetAnnotCount(FPDF_PAGE page);
FFI_PLUGIN_EXPORT FPDF_ANNOTATION PDFIUM_FPDFPage_GetAnnot(FPDF_PAGE page,int index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPage_GetAnnotIndex(FPDF_PAGE page,FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_CloseAnnot(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_RemoveAnnot(FPDF_PAGE page,int index);
FFI_PLUGIN_EXPORT FPDF_ANNOTATION_SUBTYPE PDFIUM_FPDFAnnot_GetSubtype(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_IsObjectSupportedSubtype(FPDF_ANNOTATION_SUBTYPE subtype);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_UpdateObject(FPDF_ANNOTATION annot,FPDF_PAGEOBJECT obj);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_AddInkStroke(FPDF_ANNOTATION annot,const FS_POINTF * points,size_t point_count);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_RemoveInkList(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_AppendObject(FPDF_ANNOTATION annot,FPDF_PAGEOBJECT obj);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetObjectCount(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFAnnot_GetObject(FPDF_ANNOTATION annot,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_RemoveObject(FPDF_ANNOTATION annot,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetColor(FPDF_ANNOTATION annot,FPDFANNOT_COLORTYPE type,unsigned int R,unsigned int G,unsigned int B,unsigned int A);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetColor(FPDF_ANNOTATION annot,FPDFANNOT_COLORTYPE type,unsigned int * R,unsigned int * G,unsigned int * B,unsigned int * A);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_HasAttachmentPoints(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetAttachmentPoints(FPDF_ANNOTATION annot,size_t quad_index,const FS_QUADPOINTSF * quad_points);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_AppendAttachmentPoints(FPDF_ANNOTATION annot,const FS_QUADPOINTSF * quad_points);
FFI_PLUGIN_EXPORT size_t PDFIUM_FPDFAnnot_CountAttachmentPoints(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetAttachmentPoints(FPDF_ANNOTATION annot,size_t quad_index,FS_QUADPOINTSF * quad_points);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetRect(FPDF_ANNOTATION annot,const FS_RECTF * rect);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetRect(FPDF_ANNOTATION annot,FS_RECTF * rect);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetVertices(FPDF_ANNOTATION annot,FS_POINTF * buffer,unsigned long length);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetInkListCount(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetInkListPath(FPDF_ANNOTATION annot,unsigned long path_index,FS_POINTF * buffer,unsigned long length);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetLine(FPDF_ANNOTATION annot,FS_POINTF * start,FS_POINTF * end);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetBorder(FPDF_ANNOTATION annot,float horizontal_radius,float vertical_radius,float border_width);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetBorder(FPDF_ANNOTATION annot,float * horizontal_radius,float * vertical_radius,float * border_width);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetFormAdditionalActionJavaScript(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot,int event,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_HasKey(FPDF_ANNOTATION annot,FPDF_BYTESTRING key);
FFI_PLUGIN_EXPORT FPDF_OBJECT_TYPE PDFIUM_FPDFAnnot_GetValueType(FPDF_ANNOTATION annot,FPDF_BYTESTRING key);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetStringValue(FPDF_ANNOTATION annot,FPDF_BYTESTRING key,FPDF_WIDESTRING value);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetStringValue(FPDF_ANNOTATION annot,FPDF_BYTESTRING key,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetNumberValue(FPDF_ANNOTATION annot,FPDF_BYTESTRING key,float * value);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetAP(FPDF_ANNOTATION annot,FPDF_ANNOT_APPEARANCEMODE appearanceMode,FPDF_WIDESTRING value);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetAP(FPDF_ANNOTATION annot,FPDF_ANNOT_APPEARANCEMODE appearanceMode,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_ANNOTATION PDFIUM_FPDFAnnot_GetLinkedAnnot(FPDF_ANNOTATION annot,FPDF_BYTESTRING key);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetFlags(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetFlags(FPDF_ANNOTATION annot,int flags);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetFormFieldFlags(FPDF_FORMHANDLE handle,FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_ANNOTATION PDFIUM_FPDFAnnot_GetFormFieldAtPoint(FPDF_FORMHANDLE hHandle,FPDF_PAGE page,const FS_POINTF * point);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetFormFieldName(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetFormFieldAlternateName(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetFormFieldType(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetFormFieldValue(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetOptionCount(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetOptionLabel(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot,int index,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_IsOptionSelected(FPDF_FORMHANDLE handle,FPDF_ANNOTATION annot,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetFontSize(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot,float * value);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_IsChecked(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetFocusableSubtypes(FPDF_FORMHANDLE hHandle,const FPDF_ANNOTATION_SUBTYPE * subtypes,size_t count);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetFocusableSubtypesCount(FPDF_FORMHANDLE hHandle);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_GetFocusableSubtypes(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION_SUBTYPE * subtypes,size_t count);
FFI_PLUGIN_EXPORT FPDF_LINK PDFIUM_FPDFAnnot_GetLink(FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetFormControlCount(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAnnot_GetFormControlIndex(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAnnot_GetFormFieldExportValue(FPDF_FORMHANDLE hHandle,FPDF_ANNOTATION annot,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAnnot_SetURI(FPDF_ANNOTATION annot,const char * uri);
#include "pdfium/fpdf_flatten.h"
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPage_Flatten(FPDF_PAGE page,int nFlag);
#include "pdfium/fpdf_searchex.h"
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetCharIndexFromTextIndex(FPDF_TEXTPAGE text_page,int nTextIndex);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetTextIndexFromCharIndex(FPDF_TEXTPAGE text_page,int nCharIndex);
#include "pdfium/fpdf_save.h"
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_SaveAsCopy(FPDF_DOCUMENT document,FPDF_FILEWRITE * pFileWrite,FPDF_DWORD flags);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_SaveWithVersion(FPDF_DOCUMENT document,FPDF_FILEWRITE * pFileWrite,FPDF_DWORD flags,int fileVersion);
#include "pdfium/fpdf_doc.h"
FFI_PLUGIN_EXPORT FPDF_BOOKMARK PDFIUM_FPDFBookmark_GetFirstChild(FPDF_DOCUMENT document,FPDF_BOOKMARK bookmark);
FFI_PLUGIN_EXPORT FPDF_BOOKMARK PDFIUM_FPDFBookmark_GetNextSibling(FPDF_DOCUMENT document,FPDF_BOOKMARK bookmark);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFBookmark_GetTitle(FPDF_BOOKMARK bookmark,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFBookmark_GetCount(FPDF_BOOKMARK bookmark);
FFI_PLUGIN_EXPORT FPDF_BOOKMARK PDFIUM_FPDFBookmark_Find(FPDF_DOCUMENT document,FPDF_WIDESTRING title);
FFI_PLUGIN_EXPORT FPDF_DEST PDFIUM_FPDFBookmark_GetDest(FPDF_DOCUMENT document,FPDF_BOOKMARK bookmark);
FFI_PLUGIN_EXPORT FPDF_ACTION PDFIUM_FPDFBookmark_GetAction(FPDF_BOOKMARK bookmark);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAction_GetType(FPDF_ACTION action);
FFI_PLUGIN_EXPORT FPDF_DEST PDFIUM_FPDFAction_GetDest(FPDF_DOCUMENT document,FPDF_ACTION action);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAction_GetFilePath(FPDF_ACTION action,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAction_GetURIPath(FPDF_DOCUMENT document,FPDF_ACTION action,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFDest_GetDestPageIndex(FPDF_DOCUMENT document,FPDF_DEST dest);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFDest_GetView(FPDF_DEST dest,unsigned long * pNumParams,FS_FLOAT * pParams);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFDest_GetLocationInPage(FPDF_DEST dest,FPDF_BOOL * hasXVal,FPDF_BOOL * hasYVal,FPDF_BOOL * hasZoomVal,FS_FLOAT * x,FS_FLOAT * y,FS_FLOAT * zoom);
FFI_PLUGIN_EXPORT FPDF_LINK PDFIUM_FPDFLink_GetLinkAtPoint(FPDF_PAGE page,double x,double y);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFLink_GetLinkZOrderAtPoint(FPDF_PAGE page,double x,double y);
FFI_PLUGIN_EXPORT FPDF_DEST PDFIUM_FPDFLink_GetDest(FPDF_DOCUMENT document,FPDF_LINK link);
FFI_PLUGIN_EXPORT FPDF_ACTION PDFIUM_FPDFLink_GetAction(FPDF_LINK link);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFLink_Enumerate(FPDF_PAGE page,int * start_pos,FPDF_LINK * link_annot);
FFI_PLUGIN_EXPORT FPDF_ANNOTATION PDFIUM_FPDFLink_GetAnnot(FPDF_PAGE page,FPDF_LINK link_annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFLink_GetAnnotRect(FPDF_LINK link_annot,FS_RECTF * rect);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFLink_CountQuadPoints(FPDF_LINK link_annot);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFLink_GetQuadPoints(FPDF_LINK link_annot,int quad_index,FS_QUADPOINTSF * quad_points);
FFI_PLUGIN_EXPORT FPDF_ACTION PDFIUM_FPDF_GetPageAAction(FPDF_PAGE page,int aa_type);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetFileIdentifier(FPDF_DOCUMENT document,FPDF_FILEIDTYPE id_type,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetMetaText(FPDF_DOCUMENT document,FPDF_BYTESTRING tag,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetPageLabel(FPDF_DOCUMENT document,int page_index,void * buffer,unsigned long buflen);
#include "pdfium/fpdf_formfill.h"
FFI_PLUGIN_EXPORT FPDF_FORMHANDLE PDFIUM_FPDFDOC_InitFormFillEnvironment(FPDF_DOCUMENT document,FPDF_FORMFILLINFO * formInfo);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFDOC_ExitFormFillEnvironment(FPDF_FORMHANDLE hHandle);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPage_HasFormFieldAtPoint(FPDF_FORMHANDLE hHandle,FPDF_PAGE page,double page_x,double page_y);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPage_FormFieldZOrderAtPoint(FPDF_FORMHANDLE hHandle,FPDF_PAGE page,double page_x,double page_y);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_SetFormFieldHighlightColor(FPDF_FORMHANDLE hHandle,int fieldType,unsigned long color);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_SetFormFieldHighlightAlpha(FPDF_FORMHANDLE hHandle,unsigned char alpha);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_RemoveFormFieldHighlight(FPDF_FORMHANDLE hHandle);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_FFLDraw(FPDF_FORMHANDLE hHandle,FPDF_BITMAP bitmap,FPDF_PAGE page,int start_x,int start_y,int size_x,int size_y,int rotate,int flags);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_GetFormType(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_LoadXFA(FPDF_DOCUMENT document);
#include "pdfium/fpdf_fwlevent.h"
#include "pdfium/fpdf_signature.h"
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_GetSignatureCount(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_SIGNATURE PDFIUM_FPDF_GetSignatureObject(FPDF_DOCUMENT document,int index);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFSignatureObj_GetContents(FPDF_SIGNATURE signature,void * buffer,unsigned long length);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFSignatureObj_GetByteRange(FPDF_SIGNATURE signature,int * buffer,unsigned long length);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFSignatureObj_GetSubFilter(FPDF_SIGNATURE signature,char * buffer,unsigned long length);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFSignatureObj_GetReason(FPDF_SIGNATURE signature,void * buffer,unsigned long length);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFSignatureObj_GetTime(FPDF_SIGNATURE signature,char * buffer,unsigned long length);
FFI_PLUGIN_EXPORT unsigned int PDFIUM_FPDFSignatureObj_GetDocMDPPermission(FPDF_SIGNATURE signature);
#include "pdfium/fpdf_structtree.h"
FFI_PLUGIN_EXPORT FPDF_STRUCTTREE PDFIUM_FPDF_StructTree_GetForPage(FPDF_PAGE page);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_StructTree_Close(FPDF_STRUCTTREE struct_tree);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructTree_CountChildren(FPDF_STRUCTTREE struct_tree);
FFI_PLUGIN_EXPORT FPDF_STRUCTELEMENT PDFIUM_FPDF_StructTree_GetChildAtIndex(FPDF_STRUCTTREE struct_tree,int index);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetAltText(FPDF_STRUCTELEMENT struct_element,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetActualText(FPDF_STRUCTELEMENT struct_element,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetID(FPDF_STRUCTELEMENT struct_element,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetLang(FPDF_STRUCTELEMENT struct_element,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetStringAttribute(FPDF_STRUCTELEMENT struct_element,FPDF_BYTESTRING attr_name,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructElement_GetMarkedContentID(FPDF_STRUCTELEMENT struct_element);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetType(FPDF_STRUCTELEMENT struct_element,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetObjType(FPDF_STRUCTELEMENT struct_element,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_StructElement_GetTitle(FPDF_STRUCTELEMENT struct_element,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructElement_CountChildren(FPDF_STRUCTELEMENT struct_element);
FFI_PLUGIN_EXPORT FPDF_STRUCTELEMENT PDFIUM_FPDF_StructElement_GetChildAtIndex(FPDF_STRUCTELEMENT struct_element,int index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructElement_GetChildMarkedContentID(FPDF_STRUCTELEMENT struct_element,int index);
FFI_PLUGIN_EXPORT FPDF_STRUCTELEMENT PDFIUM_FPDF_StructElement_GetParent(FPDF_STRUCTELEMENT struct_element);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructElement_GetAttributeCount(FPDF_STRUCTELEMENT struct_element);
FFI_PLUGIN_EXPORT FPDF_STRUCTELEMENT_ATTR PDFIUM_FPDF_StructElement_GetAttributeAtIndex(FPDF_STRUCTELEMENT struct_element,int index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructElement_Attr_GetCount(FPDF_STRUCTELEMENT_ATTR struct_attribute);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_StructElement_Attr_GetName(FPDF_STRUCTELEMENT_ATTR struct_attribute,int index,void * buffer,unsigned long buflen,unsigned long * out_buflen);
FFI_PLUGIN_EXPORT FPDF_OBJECT_TYPE PDFIUM_FPDF_StructElement_Attr_GetType(FPDF_STRUCTELEMENT_ATTR struct_attribute,FPDF_BYTESTRING name);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_StructElement_Attr_GetBooleanValue(FPDF_STRUCTELEMENT_ATTR struct_attribute,FPDF_BYTESTRING name,FPDF_BOOL * out_value);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_StructElement_Attr_GetNumberValue(FPDF_STRUCTELEMENT_ATTR struct_attribute,FPDF_BYTESTRING name,float * out_value);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_StructElement_Attr_GetStringValue(FPDF_STRUCTELEMENT_ATTR struct_attribute,FPDF_BYTESTRING name,void * buffer,unsigned long buflen,unsigned long * out_buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_StructElement_Attr_GetBlobValue(FPDF_STRUCTELEMENT_ATTR struct_attribute,FPDF_BYTESTRING name,void * buffer,unsigned long buflen,unsigned long * out_buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructElement_GetMarkedContentIdCount(FPDF_STRUCTELEMENT struct_element);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_StructElement_GetMarkedContentIdAtIndex(FPDF_STRUCTELEMENT struct_element,int index);
#include "pdfium/fpdf_ppo.h"
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_ImportPagesByIndex(FPDF_DOCUMENT dest_doc,FPDF_DOCUMENT src_doc,const int * page_indices,unsigned long length,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_ImportPages(FPDF_DOCUMENT dest_doc,FPDF_DOCUMENT src_doc,FPDF_BYTESTRING pagerange,int index);
FFI_PLUGIN_EXPORT FPDF_DOCUMENT PDFIUM_FPDF_ImportNPagesToOne(FPDF_DOCUMENT src_doc,float output_width,float output_height,size_t num_pages_on_x_axis,size_t num_pages_on_y_axis);
FFI_PLUGIN_EXPORT FPDF_XOBJECT PDFIUM_FPDF_NewXObjectFromPage(FPDF_DOCUMENT dest_doc,FPDF_DOCUMENT src_doc,int src_page_index);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_CloseXObject(FPDF_XOBJECT xobject);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDF_NewFormObjectFromXObject(FPDF_XOBJECT xobject);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_CopyViewerPreferences(FPDF_DOCUMENT dest_doc,FPDF_DOCUMENT src_doc);
#include "pdfium/fpdfview.h"
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_InitLibraryWithConfig(const FPDF_LIBRARY_CONFIG * config);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_InitLibrary();
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_DestroyLibrary();
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_SetSandBoxPolicy(FPDF_DWORD policy,FPDF_BOOL enable);
FFI_PLUGIN_EXPORT FPDF_DOCUMENT PDFIUM_FPDF_LoadDocument(FPDF_STRING file_path,FPDF_BYTESTRING password);
FFI_PLUGIN_EXPORT FPDF_DOCUMENT PDFIUM_FPDF_LoadMemDocument(const void * data_buf,int size,FPDF_BYTESTRING password);
FFI_PLUGIN_EXPORT FPDF_DOCUMENT PDFIUM_FPDF_LoadMemDocument64(const void * data_buf,size_t size,FPDF_BYTESTRING password);
FFI_PLUGIN_EXPORT FPDF_DOCUMENT PDFIUM_FPDF_LoadCustomDocument(FPDF_FILEACCESS * pFileAccess,FPDF_BYTESTRING password);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_GetFileVersion(FPDF_DOCUMENT doc,int * fileVersion);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetLastError();
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_DocumentHasValidCrossReferenceTable(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetTrailerEnds(FPDF_DOCUMENT document,unsigned int * buffer,unsigned long length);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetDocPermissions(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetDocUserPermissions(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_GetSecurityHandlerRevision(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_GetPageCount(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_PAGE PDFIUM_FPDF_LoadPage(FPDF_DOCUMENT document,int page_index);
FFI_PLUGIN_EXPORT float PDFIUM_FPDF_GetPageWidthF(FPDF_PAGE page);
FFI_PLUGIN_EXPORT double PDFIUM_FPDF_GetPageWidth(FPDF_PAGE page);
FFI_PLUGIN_EXPORT float PDFIUM_FPDF_GetPageHeightF(FPDF_PAGE page);
FFI_PLUGIN_EXPORT double PDFIUM_FPDF_GetPageHeight(FPDF_PAGE page);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_GetPageBoundingBox(FPDF_PAGE page,FS_RECTF * rect);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_GetPageSizeByIndexF(FPDF_DOCUMENT document,int page_index,FS_SIZEF * size);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_GetPageSizeByIndex(FPDF_DOCUMENT document,int page_index,double * width,double * height);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_RenderPageBitmap(FPDF_BITMAP bitmap,FPDF_PAGE page,int start_x,int start_y,int size_x,int size_y,int rotate,int flags);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_RenderPageBitmapWithMatrix(FPDF_BITMAP bitmap,FPDF_PAGE page,const FS_MATRIX * matrix,const FS_RECTF * clipping,int flags);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_ClosePage(FPDF_PAGE page);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_CloseDocument(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_DeviceToPage(FPDF_PAGE page,int start_x,int start_y,int size_x,int size_y,int rotate,int device_x,int device_y,double * page_x,double * page_y);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_PageToDevice(FPDF_PAGE page,int start_x,int start_y,int size_x,int size_y,int rotate,double page_x,double page_y,int * device_x,int * device_y);
FFI_PLUGIN_EXPORT FPDF_BITMAP PDFIUM_FPDFBitmap_Create(int width,int height,int alpha);
FFI_PLUGIN_EXPORT FPDF_BITMAP PDFIUM_FPDFBitmap_CreateEx(int width,int height,int format,void * first_scan,int stride);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFBitmap_GetFormat(FPDF_BITMAP bitmap);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFBitmap_FillRect(FPDF_BITMAP bitmap,int left,int top,int width,int height,FPDF_DWORD color);
FFI_PLUGIN_EXPORT void * PDFIUM_FPDFBitmap_GetBuffer(FPDF_BITMAP bitmap);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFBitmap_GetWidth(FPDF_BITMAP bitmap);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFBitmap_GetHeight(FPDF_BITMAP bitmap);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFBitmap_GetStride(FPDF_BITMAP bitmap);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFBitmap_Destroy(FPDF_BITMAP bitmap);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_VIEWERREF_GetPrintScaling(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_VIEWERREF_GetNumCopies(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_PAGERANGE PDFIUM_FPDF_VIEWERREF_GetPrintPageRange(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT size_t PDFIUM_FPDF_VIEWERREF_GetPrintPageRangeCount(FPDF_PAGERANGE pagerange);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_VIEWERREF_GetPrintPageRangeElement(FPDF_PAGERANGE pagerange,size_t index);
FFI_PLUGIN_EXPORT FPDF_DUPLEXTYPE PDFIUM_FPDF_VIEWERREF_GetDuplex(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_VIEWERREF_GetName(FPDF_DOCUMENT document,FPDF_BYTESTRING key,char * buffer,unsigned long length);
FFI_PLUGIN_EXPORT FPDF_DWORD PDFIUM_FPDF_CountNamedDests(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_DEST PDFIUM_FPDF_GetNamedDestByName(FPDF_DOCUMENT document,FPDF_BYTESTRING name);
FFI_PLUGIN_EXPORT FPDF_DEST PDFIUM_FPDF_GetNamedDest(FPDF_DOCUMENT document,int index,void * buffer,long * buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_GetXFAPacketCount(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDF_GetXFAPacketName(FPDF_DOCUMENT document,int index,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_GetXFAPacketContent(FPDF_DOCUMENT document,int index,void * buffer,unsigned long buflen,unsigned long * out_buflen);
#include "pdfium/fpdf_catalog.h"
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFCatalog_IsTagged(FPDF_DOCUMENT document);
#include "pdfium/fpdf_edit.h"
FFI_PLUGIN_EXPORT FPDF_DOCUMENT PDFIUM_FPDF_CreateNewDocument();
FFI_PLUGIN_EXPORT FPDF_PAGE PDFIUM_FPDFPage_New(FPDF_DOCUMENT document,int page_index,double width,double height);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_Delete(FPDF_DOCUMENT document,int page_index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDF_MovePages(FPDF_DOCUMENT document,const int * page_indices,unsigned long page_indices_len,int dest_page_index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPage_GetRotation(FPDF_PAGE page);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_SetRotation(FPDF_PAGE page,int rotate);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_InsertObject(FPDF_PAGE page,FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_RemoveObject(FPDF_PAGE page,FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPage_CountObjects(FPDF_PAGE page);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFPage_GetObject(FPDF_PAGE page,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_HasTransparency(FPDF_PAGE page);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPage_GenerateContent(FPDF_PAGE page);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPageObj_Destroy(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_HasTransparency(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPageObj_GetType(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPageObj_Transform(FPDF_PAGEOBJECT page_object,double a,double b,double c,double d,double e,double f);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetMatrix(FPDF_PAGEOBJECT page_object,FS_MATRIX * matrix);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetMatrix(FPDF_PAGEOBJECT page_object,const FS_MATRIX * matrix);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPage_TransformAnnots(FPDF_PAGE page,double a,double b,double c,double d,double e,double f);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFPageObj_NewImageObj(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPageObj_CountMarks(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECTMARK PDFIUM_FPDFPageObj_GetMark(FPDF_PAGEOBJECT page_object,unsigned long index);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECTMARK PDFIUM_FPDFPageObj_AddMark(FPDF_PAGEOBJECT page_object,FPDF_BYTESTRING name);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_RemoveMark(FPDF_PAGEOBJECT page_object,FPDF_PAGEOBJECTMARK mark);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_GetName(FPDF_PAGEOBJECTMARK mark,void * buffer,unsigned long buflen,unsigned long * out_buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPageObjMark_CountParams(FPDF_PAGEOBJECTMARK mark);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_GetParamKey(FPDF_PAGEOBJECTMARK mark,unsigned long index,void * buffer,unsigned long buflen,unsigned long * out_buflen);
FFI_PLUGIN_EXPORT FPDF_OBJECT_TYPE PDFIUM_FPDFPageObjMark_GetParamValueType(FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_GetParamIntValue(FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key,int * out_value);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_GetParamStringValue(FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key,void * buffer,unsigned long buflen,unsigned long * out_buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_GetParamBlobValue(FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key,void * buffer,unsigned long buflen,unsigned long * out_buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_SetIntParam(FPDF_DOCUMENT document,FPDF_PAGEOBJECT page_object,FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key,int value);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_SetStringParam(FPDF_DOCUMENT document,FPDF_PAGEOBJECT page_object,FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key,FPDF_BYTESTRING value);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_SetBlobParam(FPDF_DOCUMENT document,FPDF_PAGEOBJECT page_object,FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key,void * value,unsigned long value_len);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObjMark_RemoveParam(FPDF_PAGEOBJECT page_object,FPDF_PAGEOBJECTMARK mark,FPDF_BYTESTRING key);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFImageObj_LoadJpegFile(FPDF_PAGE * pages,int count,FPDF_PAGEOBJECT image_object,FPDF_FILEACCESS * file_access);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFImageObj_LoadJpegFileInline(FPDF_PAGE * pages,int count,FPDF_PAGEOBJECT image_object,FPDF_FILEACCESS * file_access);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFImageObj_SetMatrix(FPDF_PAGEOBJECT image_object,double a,double b,double c,double d,double e,double f);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFImageObj_SetBitmap(FPDF_PAGE * pages,int count,FPDF_PAGEOBJECT image_object,FPDF_BITMAP bitmap);
FFI_PLUGIN_EXPORT FPDF_BITMAP PDFIUM_FPDFImageObj_GetBitmap(FPDF_PAGEOBJECT image_object);
FFI_PLUGIN_EXPORT FPDF_BITMAP PDFIUM_FPDFImageObj_GetRenderedBitmap(FPDF_DOCUMENT document,FPDF_PAGE page,FPDF_PAGEOBJECT image_object);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFImageObj_GetImageDataDecoded(FPDF_PAGEOBJECT image_object,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFImageObj_GetImageDataRaw(FPDF_PAGEOBJECT image_object,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFImageObj_GetImageFilterCount(FPDF_PAGEOBJECT image_object);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFImageObj_GetImageFilter(FPDF_PAGEOBJECT image_object,int index,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFImageObj_GetImageMetadata(FPDF_PAGEOBJECT image_object,FPDF_PAGE page,FPDF_IMAGEOBJ_METADATA * metadata);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFImageObj_GetImagePixelSize(FPDF_PAGEOBJECT image_object,unsigned int * width,unsigned int * height);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFPageObj_CreateNewPath(float x,float y);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFPageObj_CreateNewRect(float x,float y,float w,float h);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetBounds(FPDF_PAGEOBJECT page_object,float * left,float * bottom,float * right,float * top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetRotatedBounds(FPDF_PAGEOBJECT page_object,FS_QUADPOINTSF * quad_points);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFPageObj_SetBlendMode(FPDF_PAGEOBJECT page_object,FPDF_BYTESTRING blend_mode);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetStrokeColor(FPDF_PAGEOBJECT page_object,unsigned int R,unsigned int G,unsigned int B,unsigned int A);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetStrokeColor(FPDF_PAGEOBJECT page_object,unsigned int * R,unsigned int * G,unsigned int * B,unsigned int * A);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetStrokeWidth(FPDF_PAGEOBJECT page_object,float width);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetStrokeWidth(FPDF_PAGEOBJECT page_object,float * width);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPageObj_GetLineJoin(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetLineJoin(FPDF_PAGEOBJECT page_object,int line_join);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPageObj_GetLineCap(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetLineCap(FPDF_PAGEOBJECT page_object,int line_cap);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetFillColor(FPDF_PAGEOBJECT page_object,unsigned int R,unsigned int G,unsigned int B,unsigned int A);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetFillColor(FPDF_PAGEOBJECT page_object,unsigned int * R,unsigned int * G,unsigned int * B,unsigned int * A);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetDashPhase(FPDF_PAGEOBJECT page_object,float * phase);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetDashPhase(FPDF_PAGEOBJECT page_object,float phase);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPageObj_GetDashCount(FPDF_PAGEOBJECT page_object);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_GetDashArray(FPDF_PAGEOBJECT page_object,float * dash_array,size_t dash_count);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPageObj_SetDashArray(FPDF_PAGEOBJECT page_object,const float * dash_array,size_t dash_count,float phase);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPath_CountSegments(FPDF_PAGEOBJECT path);
FFI_PLUGIN_EXPORT FPDF_PATHSEGMENT PDFIUM_FPDFPath_GetPathSegment(FPDF_PAGEOBJECT path,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPathSegment_GetPoint(FPDF_PATHSEGMENT segment,float * x,float * y);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFPathSegment_GetType(FPDF_PATHSEGMENT segment);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPathSegment_GetClose(FPDF_PATHSEGMENT segment);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPath_MoveTo(FPDF_PAGEOBJECT path,float x,float y);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPath_LineTo(FPDF_PAGEOBJECT path,float x,float y);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPath_BezierTo(FPDF_PAGEOBJECT path,float x1,float y1,float x2,float y2,float x3,float y3);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPath_Close(FPDF_PAGEOBJECT path);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPath_SetDrawMode(FPDF_PAGEOBJECT path,int fillmode,FPDF_BOOL stroke);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFPath_GetDrawMode(FPDF_PAGEOBJECT path,int * fillmode,FPDF_BOOL * stroke);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFPageObj_NewTextObj(FPDF_DOCUMENT document,FPDF_BYTESTRING font,float font_size);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_SetText(FPDF_PAGEOBJECT text_object,FPDF_WIDESTRING text);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_SetCharcodes(FPDF_PAGEOBJECT text_object,const uint32_t * charcodes,size_t count);
FFI_PLUGIN_EXPORT FPDF_FONT PDFIUM_FPDFText_LoadFont(FPDF_DOCUMENT document,const uint8_t * data,uint32_t size,int font_type,FPDF_BOOL cid);
FFI_PLUGIN_EXPORT FPDF_FONT PDFIUM_FPDFText_LoadStandardFont(FPDF_DOCUMENT document,FPDF_BYTESTRING font);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFTextObj_GetFontSize(FPDF_PAGEOBJECT text,float * size);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFFont_Close(FPDF_FONT font);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFPageObj_CreateTextObj(FPDF_DOCUMENT document,FPDF_FONT font,float font_size);
FFI_PLUGIN_EXPORT FPDF_TEXT_RENDERMODE PDFIUM_FPDFTextObj_GetTextRenderMode(FPDF_PAGEOBJECT text);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFTextObj_SetTextRenderMode(FPDF_PAGEOBJECT text,FPDF_TEXT_RENDERMODE render_mode);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFTextObj_GetText(FPDF_PAGEOBJECT text_object,FPDF_TEXTPAGE text_page,FPDF_WCHAR * buffer,unsigned long length);
FFI_PLUGIN_EXPORT FPDF_BITMAP PDFIUM_FPDFTextObj_GetRenderedBitmap(FPDF_DOCUMENT document,FPDF_PAGE page,FPDF_PAGEOBJECT text_object,float scale);
FFI_PLUGIN_EXPORT FPDF_FONT PDFIUM_FPDFTextObj_GetFont(FPDF_PAGEOBJECT text);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFFont_GetFontName(FPDF_FONT font,char * buffer,unsigned long length);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFFont_GetFontData(FPDF_FONT font,uint8_t * buffer,size_t buflen,size_t * out_buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFFont_GetIsEmbedded(FPDF_FONT font);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFFont_GetFlags(FPDF_FONT font);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFFont_GetWeight(FPDF_FONT font);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFFont_GetItalicAngle(FPDF_FONT font,int * angle);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFFont_GetAscent(FPDF_FONT font,float font_size,float * ascent);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFFont_GetDescent(FPDF_FONT font,float font_size,float * descent);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFFont_GetGlyphWidth(FPDF_FONT font,uint32_t glyph,float font_size,float * width);
FFI_PLUGIN_EXPORT FPDF_GLYPHPATH PDFIUM_FPDFFont_GetGlyphPath(FPDF_FONT font,uint32_t glyph,float font_size);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFGlyphPath_CountGlyphSegments(FPDF_GLYPHPATH glyphpath);
FFI_PLUGIN_EXPORT FPDF_PATHSEGMENT PDFIUM_FPDFGlyphPath_GetGlyphPathSegment(FPDF_GLYPHPATH glyphpath,int index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFFormObj_CountObjects(FPDF_PAGEOBJECT form_object);
FFI_PLUGIN_EXPORT FPDF_PAGEOBJECT PDFIUM_FPDFFormObj_GetObject(FPDF_PAGEOBJECT form_object,unsigned long index);
#include "pdfium/fpdf_thumbnail.h"
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFPage_GetDecodedThumbnailData(FPDF_PAGE page,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFPage_GetRawThumbnailData(FPDF_PAGE page,void * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BITMAP PDFIUM_FPDFPage_GetThumbnailAsBitmap(FPDF_PAGE page);
#include "pdfium/fpdf_javascript.h"
FFI_PLUGIN_EXPORT int PDFIUM_FPDFDoc_GetJavaScriptActionCount(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_JAVASCRIPT_ACTION PDFIUM_FPDFDoc_GetJavaScriptAction(FPDF_DOCUMENT document,int index);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFDoc_CloseJavaScriptAction(FPDF_JAVASCRIPT_ACTION javascript);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFJavaScriptAction_GetName(FPDF_JAVASCRIPT_ACTION javascript,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFJavaScriptAction_GetScript(FPDF_JAVASCRIPT_ACTION javascript,FPDF_WCHAR * buffer,unsigned long buflen);
#include "pdfium/fpdf_sysfontinfo.h"
FFI_PLUGIN_EXPORT const FPDF_CharsetFontMap * PDFIUM_FPDF_GetDefaultTTFMap();
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_AddInstalledFont(void * mapper,const char * face,int charset);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_SetSystemFontInfo(FPDF_SYSFONTINFO * pFontInfo);
FFI_PLUGIN_EXPORT FPDF_SYSFONTINFO * PDFIUM_FPDF_GetDefaultSystemFontInfo();
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_FreeDefaultSystemFontInfo(FPDF_SYSFONTINFO * pFontInfo);
#include "pdfium/fpdf_dataavail.h"
FFI_PLUGIN_EXPORT FPDF_AVAIL PDFIUM_FPDFAvail_Create(FX_FILEAVAIL * file_avail,FPDF_FILEACCESS * file);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFAvail_Destroy(FPDF_AVAIL avail);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAvail_IsDocAvail(FPDF_AVAIL avail,FX_DOWNLOADHINTS * hints);
FFI_PLUGIN_EXPORT FPDF_DOCUMENT PDFIUM_FPDFAvail_GetDocument(FPDF_AVAIL avail,FPDF_BYTESTRING password);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAvail_GetFirstPageNum(FPDF_DOCUMENT doc);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAvail_IsPageAvail(FPDF_AVAIL avail,int page_index,FX_DOWNLOADHINTS * hints);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAvail_IsFormAvail(FPDF_AVAIL avail,FX_DOWNLOADHINTS * hints);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFAvail_IsLinearized(FPDF_AVAIL avail);
#include "pdfium/fpdf_progressive.h"
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_RenderPageBitmapWithColorScheme_Start(FPDF_BITMAP bitmap,FPDF_PAGE page,int start_x,int start_y,int size_x,int size_y,int rotate,int flags,const FPDF_COLORSCHEME * color_scheme,IFSDK_PAUSE * pause);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_RenderPageBitmap_Start(FPDF_BITMAP bitmap,FPDF_PAGE page,int start_x,int start_y,int size_x,int size_y,int rotate,int flags,IFSDK_PAUSE * pause);
FFI_PLUGIN_EXPORT int PDFIUM_FPDF_RenderPage_Continue(FPDF_PAGE page,IFSDK_PAUSE * pause);
FFI_PLUGIN_EXPORT void PDFIUM_FPDF_RenderPage_Close(FPDF_PAGE page);
#include "pdfium/fpdf_text.h"
FFI_PLUGIN_EXPORT FPDF_TEXTPAGE PDFIUM_FPDFText_LoadPage(FPDF_PAGE page);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFText_ClosePage(FPDF_TEXTPAGE text_page);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_CountChars(FPDF_TEXTPAGE text_page);
FFI_PLUGIN_EXPORT unsigned int PDFIUM_FPDFText_GetUnicode(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_IsGenerated(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_IsHyphen(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_HasUnicodeMapError(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT double PDFIUM_FPDFText_GetFontSize(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFText_GetFontInfo(FPDF_TEXTPAGE text_page,int index,void * buffer,unsigned long buflen,int * flags);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetFontWeight(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT FPDF_TEXT_RENDERMODE PDFIUM_FPDFText_GetTextRenderMode(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_GetFillColor(FPDF_TEXTPAGE text_page,int index,unsigned int * R,unsigned int * G,unsigned int * B,unsigned int * A);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_GetStrokeColor(FPDF_TEXTPAGE text_page,int index,unsigned int * R,unsigned int * G,unsigned int * B,unsigned int * A);
FFI_PLUGIN_EXPORT float PDFIUM_FPDFText_GetCharAngle(FPDF_TEXTPAGE text_page,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_GetCharBox(FPDF_TEXTPAGE text_page,int index,double * left,double * right,double * bottom,double * top);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_GetLooseCharBox(FPDF_TEXTPAGE text_page,int index,FS_RECTF * rect);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_GetMatrix(FPDF_TEXTPAGE text_page,int index,FS_MATRIX * matrix);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_GetCharOrigin(FPDF_TEXTPAGE text_page,int index,double * x,double * y);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetCharIndexAtPos(FPDF_TEXTPAGE text_page,double x,double y,double xTolerance,double yTolerance);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetText(FPDF_TEXTPAGE text_page,int start_index,int count,unsigned short * result);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_CountRects(FPDF_TEXTPAGE text_page,int start_index,int count);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_GetRect(FPDF_TEXTPAGE text_page,int rect_index,double * left,double * top,double * right,double * bottom);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetBoundedText(FPDF_TEXTPAGE text_page,double left,double top,double right,double bottom,unsigned short * buffer,int buflen);
FFI_PLUGIN_EXPORT FPDF_SCHHANDLE PDFIUM_FPDFText_FindStart(FPDF_TEXTPAGE text_page,FPDF_WIDESTRING findwhat,unsigned long flags,int start_index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_FindNext(FPDF_SCHHANDLE handle);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFText_FindPrev(FPDF_SCHHANDLE handle);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetSchResultIndex(FPDF_SCHHANDLE handle);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFText_GetSchCount(FPDF_SCHHANDLE handle);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFText_FindClose(FPDF_SCHHANDLE handle);
FFI_PLUGIN_EXPORT FPDF_PAGELINK PDFIUM_FPDFLink_LoadWebLinks(FPDF_TEXTPAGE text_page);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFLink_CountWebLinks(FPDF_PAGELINK link_page);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFLink_GetURL(FPDF_PAGELINK link_page,int link_index,unsigned short * buffer,int buflen);
FFI_PLUGIN_EXPORT int PDFIUM_FPDFLink_CountRects(FPDF_PAGELINK link_page,int link_index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFLink_GetRect(FPDF_PAGELINK link_page,int link_index,int rect_index,double * left,double * top,double * right,double * bottom);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFLink_GetTextRange(FPDF_PAGELINK link_page,int link_index,int * start_char_index,int * char_count);
FFI_PLUGIN_EXPORT void PDFIUM_FPDFLink_CloseWebLinks(FPDF_PAGELINK link_page);
#include "pdfium/fpdf_ext.h"
FFI_PLUGIN_EXPORT int PDFIUM_FPDFDoc_GetPageMode(FPDF_DOCUMENT document);
#include "pdfium/fpdf_attachment.h"
FFI_PLUGIN_EXPORT int PDFIUM_FPDFDoc_GetAttachmentCount(FPDF_DOCUMENT document);
FFI_PLUGIN_EXPORT FPDF_ATTACHMENT PDFIUM_FPDFDoc_AddAttachment(FPDF_DOCUMENT document,FPDF_WIDESTRING name);
FFI_PLUGIN_EXPORT FPDF_ATTACHMENT PDFIUM_FPDFDoc_GetAttachment(FPDF_DOCUMENT document,int index);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFDoc_DeleteAttachment(FPDF_DOCUMENT document,int index);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAttachment_GetName(FPDF_ATTACHMENT attachment,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAttachment_HasKey(FPDF_ATTACHMENT attachment,FPDF_BYTESTRING key);
FFI_PLUGIN_EXPORT FPDF_OBJECT_TYPE PDFIUM_FPDFAttachment_GetValueType(FPDF_ATTACHMENT attachment,FPDF_BYTESTRING key);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAttachment_SetStringValue(FPDF_ATTACHMENT attachment,FPDF_BYTESTRING key,FPDF_WIDESTRING value);
FFI_PLUGIN_EXPORT unsigned long PDFIUM_FPDFAttachment_GetStringValue(FPDF_ATTACHMENT attachment,FPDF_BYTESTRING key,FPDF_WCHAR * buffer,unsigned long buflen);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAttachment_SetFile(FPDF_ATTACHMENT attachment,FPDF_DOCUMENT document,const void * contents,unsigned long len);
FFI_PLUGIN_EXPORT FPDF_BOOL PDFIUM_FPDFAttachment_GetFile(FPDF_ATTACHMENT attachment,void * buffer,unsigned long buflen,unsigned long * out_buflen);
